spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080  